### ISSUE TITLE
Implement multistart

### ISSUE THREAD

**Issue by calcmogul** [SleipnirGroup/Sleipnir#359]
Start parallel solvers on extra threads and return the solution with the lowest cost.

https://pyomo.readthedocs.io/en/stable/contributed_packages/multistart.html

This will require doing deep copies of the autodiff expression tree so the threads don't need to share data structures. NumPy calls the member function for doing this copy(): https://numpy.org/doc/stable/reference/generated/numpy.copy.html.

**Comment by calcmogul** [comment]
It's easier to do this on the user side. They'd write a function that constructs the problem, solves it, and returns the solution and its cost. They can spawn multiple threads with that function, then pick the solution with the lowest cost.

We can write an example for this.

**Comment by spacey-sooty** [comment]
For picking the solution with the lowest cost would you just wait till all threads are resolved then pick or say have a shared vector which the threads append to when they reach a solution then pick the lowest at an abritrary time?

**Comment by calcmogul** [comment]
If you set the solver's timeout (see SolverConfig argument of OptimizationProblem.Solve()), you could spawn the threads with `std::async()`, then call `get()` on all of them to unwrap each `std::future` containing a solution and cost.

**Comment by calcmogul** [comment]
A good test for this feature would be "Mishra's Bird function - constrained" from https://en.wikipedia.org/wiki/Test_functions_for_optimization#Test_functions_for_constrained_optimization.
