### ISSUE TITLE
Cart-pole problem iterates oscillate around infeasible location

### ISSUE THREAD

**Issue by calcmogul** [SleipnirGroup/Sleipnir#46]
The solver's iterates oscillate around an infeasible location, so the error never drops below the threshold and the max iteration count is reached. A feasibility restoration phase is needed to fix this.

Note that this is only an issue for poorly behaved cost function manifolds.

**Comment by JoshuaAN** [comment]
For reference, section 3.3 of the [http://cepac.cheme.cmu.edu/pasilectures/biegler/ipopt.pdf](IPOPT paper) describes a feasibility restoration method.
