### ISSUE TITLE
Should this conceptually give the same result as coin-or ipopt?

### ISSUE THREAD

**Issue by Neumann-A** [SleipnirGroup/Sleipnir#83]
So I have defined the following problem:
```
   sleipnir::OptimizationProblem problem;
   auto x = problem.DecisionVariable((int)in.system_matrix.cols());

   problem.SubjectTo(x >= 0);
   //problem.SubjectTo(x < 1);
   auto cost_vec_f = in.system_matrix*x-in.measurement;
   auto f = sleipnir::sqrt(cost_vec_f*cost_vec_f);  // Should really be cost_vec_f.norm()
   problem.Minimize(f);

   problem.Solve({.tolerance=1E-10,.maxIterations = 100000,.diagnostics = true});
```

In ipopt I have:
```
   f_vec = (in.system_matrix * x - in.measurement).eval();
   norm = f_vec.norm();
```
where `norm` is the cost.

While ipopt and a manually implemented barrier + fminsearch in matlab give similar results sleipnir seems not to converge to a meaningful solution. 

Did I do something wrong in defining the problem or is sleipnir not useful for constraints which are too simple ?

**Comment by calcmogul** [comment]
I suggest using a sum of squares cost function instead of a norm cost function.

The square root in a norm (square root of sum of squares) cost function is nonlinear so the Hessian changes over time and needs to be recomputed (takes longer). Furthermore, the Hessian can become ill-conditioned, which is harder for the solver to deal with. For example, the Hessian of sqrt(x²+y²) is this: https://www.wolframalpha.com/input?i=hessian+of+sqrt%28x%5E2%2By%5E2%29 with the eigenvalues [0, 1/sqrt(x²+y²)].

A squared norm (sum of squares) cost function is quadratic. Since your constraints are linear, the Hessian would be constant. For example, the Hessian of x²+y² is [2, 0; 0, 2] with the eigenvalues [2, 2].

By the way, the diagnostic prints from setting the diagnostics flag to true will tell you the linearity of your cost function and constraints. Here's some relevant docs on optimizing your problem formulation: https://sleipnirgroup.github.io/Sleipnir/classsleipnir_1_1OptimizationProblem.html#autotoc_md22

**Comment by Neumann-A** [comment]
> I suggest using a sum of squares cost function instead of a norm cost function.

Doesn't change the fact that sleipnir is not getting the correct answer. (i tested it with either)
Also unless you point me to some source discussing the benefits and drawbacks from a numerical instead of a mathematical perspective I rather stay with the normal norm. 
ipopt gets the solution in ~30 iterations. sleipnir claims to find it 4 iterations but actually fails to find it and gives a more or less constant solution across all vars. Even having a smaller tolerance doesn'T really change that. 
Is there a way to control the start point  sleipnir uses?

**Comment by calcmogul** [comment]
Could you provide some sample data and the system matrix so the problem can be reproduced?

**Comment by calcmogul** [comment]
> Is there a way to control the start point sleipnir uses?

Yes. Assign constants to the decision variables like this:
```cpp
sleipnir::OptimizationProblem problem;

auto x = problem.DecisionVariable();
x = x0;
auto y = problem.DecisionVariable();
y = y0;

problem.Minimize(sleipnir::pow(1 - x, 2) +
                 100 * sleipnir::pow(y - sleipnir::pow(x, 2), 2));

problem.SubjectTo(sleipnir::pow(x, 2) + sleipnir::pow(y, 2) <= 2);
```

**Comment by Neumann-A** [comment]
> Could you provide some sample data and the system matrix so the problem can be reproduced?

I have it in hdf5 format if you can read it:
https://github.com/Neumann-A/mpi-ipopt-reco/blob/main/data/in.h5
the expected result is the vector stored in 
https://github.com/Neumann-A/mpi-ipopt-reco/blob/main/data/out.h5

>Yes. Assign constants to the decision variables like this:

Hmm should that error?
```
   auto x = problem.DecisionVariable((int)in.system_matrix.cols());
   Eigen::VectorXd x0(in.measurement.size());
   x0.setConstant(std::numeric_limits<double>::epsilon()).eval();  //eval() just to make sure Eigen evaluates it. It crashes either way.
   x = x0;
```
gets me:
```
WARNING: E:\b\sleipnir\src\e02a33095c-d8b3829161.clean\src\autodiff\Variable.cpp:32: Modified the value of a dependent variable
Exception thrown at 0x00007FF685166259 in mpi-ipopt-reco-sleipnir.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
```

**Comment by calcmogul** [comment]
Is that repo private? I can't access those HDF5 files.

> Hmm should that error?

No. Looking into it.

**Comment by calcmogul** [comment]
If it hasn't already become apparent, Sleipnir is a new project that hasn't yet seen production use.

**Comment by Neumann-A** [comment]
> Is that repo private? I can't access those HDF5 files.

always forgot about that.. here is the data zipped in csv format.
[data.zip](https://github.com/SleipnirGroup/Sleipnir/files/10717110/data.zip)

> If it hasn't already become apparent, Sleipnir is a new project that hasn't yet seen production use.

I just stumbled across this library from the eigen3 discord so I thought I give it a try since it uses Eigen3 itself and I don't have to use the `Eigen::Map` dance required for ipopt ;). AD than was just a bonus.

**Comment by Neumann-A** [comment]
[result.txt](https://github.com/SleipnirGroup/Sleipnir/files/10717193/result.txt)
 forgot to also give the ipopt output result.

**Comment by calcmogul** [comment]
If you want a similar API to Sleipnir but something that actually works, consider [CasADi](https://github.com/casadi/casadi)'s optistack API with the ipopt backend.

CasADi has slow solver startup times, 10x slower solver iterations, and Fortran dependencies that make it hard to cross compile, but those may not be issues for you if you're just on desktop. Their Python bindings work fine on Windows, macOS, and Linux; and they also work on Raspberry Pi as far as I know if you have a Fortran compiler for pip to use.

**Comment by calcmogul** [comment]
```cpp
   auto x = problem.DecisionVariable((int)in.system_matrix.cols());
   Eigen::VectorXd x0(in.measurement.size());
   x0.setConstant(std::numeric_limits<double>::epsilon()).eval();  //eval() just to make sure Eigen evaluates it. It crashes either way.
   x = x0;
```
Looks like we need operator= overloads for dynamic Eigen matrices in addition to the static Eigen matrix overloads we already have.

**Comment by Neumann-A** [comment]
> EDIT: Should be fixed by https://github.com/SleipnirGroup/Sleipnir/pull/85.

still:
`Exception thrown at 0x00007FF6261562B9 in mpi-ipopt-reco-sleipnir.exe: 0xC0000005: Access violation reading location 0x0000000000000050.`
Not fixed. Nullptr exception in Variable.cpp at line 29. this->expr is nullptr

**Comment by calcmogul** [comment]
I wasn't saying all problems in this issue were fixed. I was saying the dynamic Eigen matrix assignment in the given snippet was fixed.

**Comment by calcmogul** [comment]
> Nullptr exception in Variable.cpp at line 29. this->expr is nullptr

Could you provide a backtrace?

**Comment by calcmogul** [comment]
```cpp
   auto x = problem.DecisionVariable((int)in.system_matrix.cols());
   Eigen::VectorXd x0(in.measurement.size());
```
The assignment of x0 to x will only work here if in.system_matrix.cols() == in.measurement.size(). Is that the case?

**Comment by Neumann-A** [comment]
> I wasn't saying all problems in this issue were fixed. I was saying the dynamic Eigen matrix assignment in the given snippet was fixed. The access violation is a separate thing.

So are you saying  `x = x0;` should work or not? Because that is the line throwing ;)

![image](https://user-images.githubusercontent.com/30894796/218341039-132c35a6-1c2d-49a6-b4bd-31cd781e2c85.png)

**Comment by calcmogul** [comment]
There's unit tests now that check assignment of a dynamic matrix, and it works without crashing.

**Comment by Neumann-A** [comment]
Ah my error. Changed it to also use `in.system_matrix.cols()`

**Comment by calcmogul** [comment]
In the Sleipnir code in the original post (case 1), the following line doesn't actually compute the norm as a 1x1 cost function:
```cpp
   auto f = sleipnir::sqrt(cost_vec_f*cost_vec_f);  // Should really be cost_vec_f.norm()
```
If `cost_vec_f` is a column vector, then `f` needs to be (case 2):
```cpp
   auto f = sleipnir::sqrt(cost_vec_f.T()*cost_vec_f);
```
In case 1, `decltype(f)` is `VariableMatrix` and Minimize() takes Variable, but we can't catch this at compile time because we need implicit conversion to Variable to work for convenience (spamming `(0)` on the end of multiplications is annoying). We could catch it at runtime with a `Minimize()` overload for `VariableMatrix` that complains if the argument isn't 1x1.
